- hosts: wsl
  gather_facts: true
  vars_files:
    - vars/language_versions.yml
    - vars/packages_ubuntu.yml
    - vars/packages_fedora.yml
    - vars/packages_alpine.yml
    - vars/tool_versions.yml
    - vars/user_environment.yml
    - vars/vimvars.yml
  roles:
    - facts
  tasks:
    - name: Run github-only git tasks
      import_role:
        name: git
        tasks_from: github.yml